INSERT INTO tb_user(first_name, last_name, email, password, user_role) VALUES ('Renato', 'Marques','email@gmail.com', '173', 'ROLE_ADMIN');
INSERT INTO tb_user(first_name, last_name, email, password, user_role) VALUES ('Gabriel', 'Marques','email@gmail.com', '173', 'ROLE_TRIADOR');
INSERT INTO tb_user(first_name, last_name, email, password, user_role) VALUES ('Ryan', 'Marques','email@gmail.com', '173', 'ROLE_FINALIZADOR');
INSERT INTO tb_user(first_name, last_name, email, password, user_role) VALUES ('Gih', 'Marques','email@gmail.com', '173', 'ROLE_ADMIN');


INSERT INTO tb_process (name, created_at, description, process_status)  VALUES ('processo 01', TIMESTAMP WITH TIME ZONE '2020-01-21T21:59:19Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'PENDENT');
INSERT INTO tb_process (name, created_at, description, process_status)  VALUES ('processo 02', TIMESTAMP WITH TIME ZONE '2020-02-21T20:59:19Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'PENDENT');
INSERT INTO tb_process (name, created_at, description, process_status)  VALUES ('processo 03', TIMESTAMP WITH TIME ZONE '2020-12-17T20:59:19Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'PENDENT');
INSERT INTO tb_process (name, created_at, description, process_status)  VALUES ('processo 04', TIMESTAMP WITH TIME ZONE '2020-07-14T20:59:19Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'PENDENT');
INSERT INTO tb_process (name, created_at, description, process_status)  VALUES ('processo 05', TIMESTAMP WITH TIME ZONE '2020-08-05T20:59:19Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'PENDENT');
